// Code generated by goyacc sint.y. DO NOT EDIT.

//line sint.y:2
package An

import __yyfmt__ "fmt"

//line sint.y:2

import (
	"bufio" // para esperar una entrada
	"bytes"
	"fmt"
	"os"
	"strings" // PARA HACER EL STRIM() EN LAS CADENAS
)

/*
un archivo .y esta compuesto por 4 secciones
- importes , uniones o declaraciones de tokenes , declaracion de gramatica , Segmento de codigo  para las funciones
*/

//line sint.y:19
type yySymType struct {
	yys         int
	NoTerminal  string
	str         string // DEFINO EL TIPO  DE MIS TERMINALES , EN ESTE CASO TODOS LOS QUE ESTEN EN %type<token> lo que va devolver es un tipo string
	tokenEntero int64
}

const NUMERO = 57346
const EXTENSION_DSK = 57347
const B = 57348
const E = 57349
const L = 57350
const RF = 57351
const BF = 57352
const FF = 57353
const WF = 57354
const K = 57355
const M = 57356
const CHGRP = 57357
const GRP = 57358
const PAUSE = 57359
const COMANDO_ID = 57360
const R = 57361
const CHOWN = 57362
const CP = 57363
const DEST = 57364
const FIND = 57365
const CAT = 57366
const MV = 57367
const RM = 57368
const REN = 57369
const P = 57370
const MKFILE = 57371
const MKDIR = 57372
const LOGOUT = 57373
const ID = 57374
const FILE_N = 57375
const EDIT = 57376
const MKGRP = 57377
const RMGRP = 57378
const USR = 57379
const MOUNT = 57380
const RMDISK = 57381
const FLECHA = 57382
const PATH = 57383
const ADD = 57384
const EXEC = 57385
const RUTA = 57386
const MKDISK = 57387
const SIZE = 57388
const NAME = 57389
const UNIT = 57390
const FDISK = 57391
const TYPE = 57392
const FIT = 57393
const DELETE = 57394
const fast = 57395
const full = 57396
const UNMOUNT = 57397
const MKFS = 57398
const PWD = 57399
const RMUSR = 57400
const MKURS = 57401
const CHMOD = 57402
const UGO = 57403
const CONT = 57404

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMERO",
	"EXTENSION_DSK",
	"B",
	"E",
	"L",
	"RF",
	"BF",
	"FF",
	"WF",
	"K",
	"M",
	"CHGRP",
	"GRP",
	"PAUSE",
	"COMANDO_ID",
	"R",
	"CHOWN",
	"CP",
	"DEST",
	"FIND",
	"CAT",
	"MV",
	"RM",
	"REN",
	"P",
	"MKFILE",
	"MKDIR",
	"LOGOUT",
	"ID",
	"FILE_N",
	"EDIT",
	"MKGRP",
	"RMGRP",
	"USR",
	"MOUNT",
	"RMDISK",
	"FLECHA",
	"PATH",
	"ADD",
	"EXEC",
	"RUTA",
	"MKDISK",
	"SIZE",
	"NAME",
	"UNIT",
	"FDISK",
	"TYPE",
	"FIT",
	"DELETE",
	"fast",
	"full",
	"UNMOUNT",
	"MKFS",
	"PWD",
	"RMUSR",
	"MKURS",
	"CHMOD",
	"UGO",
	"CONT",
	"'-'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line sint.y:119

func leerArchivoDeEntrada(ruta string) {
	fmt.Println("")
	fmt.Println("")
	fmt.Println("							||||||||||||||||||||||||||||||||||")
	fmt.Println("							|||||| Analizando un archivo |||||")
	fmt.Println("							||||||||||||||||||||||||||||||||||")
	fmt.Println("")
	ARCHIVO, error := os.Open(QuitarComillas(ruta))
	algo_salio_mal := false
	if error != nil {
		fmt.Println("ERROR REPORTADO")
		algo_salio_mal = true
	}
	if !(algo_salio_mal) {
		yyDebug = 0
		yyErrorVerbose = true
		scanner := bufio.NewScanner(ARCHIVO)
		entrada := ""
		for scanner.Scan() {
			linea_entrada := scanner.Text()
			linea_entrada = strings.TrimSpace(linea_entrada) // 	QUITO LOS ESPACIOS A LOS LADOS
			entrada = entrada + linea_entrada
			var listo_para_analizar bool = true
			// PREGUNTA SI TIENE UN CARACTER PARA CONTINUAR CON LA SIGUIENTE LINEA
			if len(entrada) >= 2 && entrada[len(entrada)-1] == '*' && entrada[len(entrada)-2] == '\\' {
				listo_para_analizar = false // TENGO QUE CONCATENAR LA ENTRADA ANTERIOR CON LA LINEA ACTUAL
				entrada = QuitarSimboloNextLine(entrada)
			}

			if listo_para_analizar {
				fmt.Println("EJECUTANDO>> " + entrada)
				l := nuevo_lexico__(bytes.NewBufferString(entrada), os.Stdout, "file.name") // ESTA FUNCION VIENE DEL ANALIZADOR LEXICO
				yyParse(l)
				entrada = "" //limpio la entrada
			}
		}
	}
	fmt.Println("")
	fmt.Println("							...Archivo terminado de analizar...")
	fmt.Println("")
}

func AnalizarComando() {
	puntero_lector := bufio.NewReader(os.NewFile(0, "stdin"))
	yyDebug = 0
	yyErrorVerbose = true
	for { // ciclo infinito
		var entrada string
		var bandera_todo_bien bool

		fmt.Printf(">> ")
		if entrada, bandera_todo_bien = leerLineComando(puntero_lector); bandera_todo_bien {
			entrada = strings.TrimSpace(entrada)

			if len(entrada) >= 2 && entrada[len(entrada)-1] == '*' && entrada[len(entrada)-2] == '\\' {
				entrada = QuitarSimboloNextLine(entrada)
				for {
					fmt.Print("continua esa linea>>")
					temporal := ""
					temporal, bandera_todo_bien = leerLineComando(puntero_lector)
					entrada += temporal
					entrada = strings.TrimSpace(entrada)
					if entrada[len(entrada)-1] != '*' && entrada[len(entrada)-2] != '\\' {
						break
					} else {
						entrada = QuitarSimboloNextLine(entrada)
					}
				}

			}
			l := nuevo_lexico__(bytes.NewBufferString(entrada), os.Stdout, "file.name") // ESTA FUNCION VIENE DEL ANALIZADOR LEXICO
			yyParse(l)
		} else {
			break
		}
	}
}

func leerLineComando(puntero_lector *bufio.Reader) (string, bool) {
	salida, err := puntero_lector.ReadString('\n')
	if err != nil {
		return "", false
	}
	return salida, true
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 88

var yyAct = [...]int{
	22, 20, 16, 17, 13, 32, 38, 68, 84, 85,
	31, 33, 34, 8, 35, 36, 37, 26, 70, 40,
	29, 87, 25, 27, 28, 41, 67, 65, 60, 58,
	69, 23, 57, 56, 12, 10, 21, 55, 54, 2,
	53, 9, 52, 51, 50, 11, 49, 48, 47, 46,
	45, 44, 43, 42, 77, 78, 74, 19, 39, 63,
	64, 86, 15, 72, 73, 88, 80, 81, 82, 61,
	66, 59, 18, 83, 75, 76, 30, 24, 71, 6,
	14, 5, 62, 4, 3, 7, 79, 1,
}

var yyPact = [...]int{
	-4, -1000, -59, -1000, -1000, -1000, -1000, -1000, -1000, -61,
	-60, -62, -63, -10, -61, -1000, -24, -21, -62, -1000,
	-36, -63, -22, 13, -1000, 12, 11, 10, 9, 8,
	-1000, 7, 6, 4, 3, 2, 0, -2, -3, -1000,
	-7, -8, -15, 67, -16, 64, 46, -17, 66, -18,
	-14, 50, 47, 56, -45, 57, -23, -14, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 87, 86, 85, 7, 84, 83, 82, 81, 80,
	62, 79, 78, 74, 73, 36, 72, 57,
}

var yyR1 = [...]int{
	0, 1, 1, 1, 5, 5, 5, 5, 5, 3,
	15, 15, 8, 6, 9, 9, 10, 10, 10, 10,
	7, 7, 12, 12, 12, 11, 16, 16, 17, 17,
	17, 17, 17, 17, 17, 17, 14, 14, 2, 2,
	2, 13, 13, 13, 4, 4,
}

var yyR2 = [...]int{
	0, 0, 5, 1, 1, 1, 1, 1, 1, 3,
	4, 4, 5, 2, 2, 1, 4, 4, 4, 4,
	1, 1, 1, 1, 1, 2, 2, 1, 4, 4,
	4, 4, 4, 4, 4, 4, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int{
	-1000, -1, 43, -5, -6, -8, -11, -3, 17, 45,
	39, 49, 38, 63, -9, -10, 63, 63, -16, -17,
	63, -15, 63, 41, -10, 46, 41, 47, 48, 41,
	-17, 46, 41, 47, 48, 50, 51, 52, 42, -15,
	41, 47, 40, 40, 40, 40, 40, 40, 40, 40,
	40, 40, 40, 40, 40, 40, 40, 40, 44, 4,
	44, 5, -7, 13, 14, 44, 4, 44, -4, 44,
	32, -12, 13, 14, 6, -13, 28, 7, 8, -2,
	10, 11, 12, -14, 53, 54, 4, 44, -4,
}

var yyDef = [...]int{
	1, -2, 0, 3, 4, 5, 6, 7, 8, 0,
	0, 0, 0, 0, 13, 15, 0, 0, 25, 27,
	0, 0, 0, 0, 14, 0, 0, 0, 0, 0,
	26, 0, 0, 0, 0, 0, 0, 0, 0, 9,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 2, 16,
	17, 18, 19, 20, 21, 12, 28, 29, 30, 44,
	45, 31, 22, 23, 24, 32, 41, 42, 43, 33,
	38, 39, 40, 34, 36, 37, 35, 10, 11,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 63,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sint.y:39
		{
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sint.y:40
		{
			leerArchivoDeEntrada(yyDollar[5].str)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:48
		{
			pausar_()
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sint.y:51
		{
			fmt.Println("INSTRUCCION")
			fmt.Println("MONTAR")
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:53
		{
			Path_ = yyDollar[4].str
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:54
		{
			Name_ = yyDollar[4].NoTerminal
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sint.y:57
		{
			EliminarDisco(yyDollar[5].str)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sint.y:59
		{
			CrearDisco(Size_, Path_, Name_, Unit_m_)
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:64
		{
			Size_ = yyDollar[4].str
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:65
		{
			Path_ = yyDollar[4].str
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:66
		{
			Name_ = yyDollar[4].str
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:67
		{
			Unit_m_ = yyDollar[4].NoTerminal
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:72
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:73
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:76
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:77
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:78
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sint.y:81
		{
			MetodosParticiones(Path_, Name_, Size_, FIT_, OPCION_DELETE_, add_, tipo_particion_, Unit_k_)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:87
		{
			Size_ = yyDollar[4].str
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:88
		{
			Path_ = yyDollar[4].str
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:89
		{
			Name_ = yyDollar[4].NoTerminal
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:90
		{
			Unit_k_ = yyDollar[4].NoTerminal
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:91
		{
			tipo_particion_ = yyDollar[4].NoTerminal
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:92
		{
			FIT_ = yyDollar[4].NoTerminal
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:93
		{
			OPCION_DELETE_ = yyDollar[4].NoTerminal
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:94
		{
			add_ = yyDollar[4].str
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:97
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:98
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:101
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:102
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:103
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:106
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:107
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:108
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:112
		{
			yyVAL.NoTerminal = QuitarComillas(yyDollar[1].str)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:113
		{
			yyVAL.NoTerminal = QuitarComillas(yyDollar[1].str)
		}
	}
	goto yystack /* stack new state and value */
}
