// Code generated by goyacc sint.y. DO NOT EDIT.

//line sint.y:2
package An

import __yyfmt__ "fmt"

//line sint.y:2

import (
	"bufio" // para esperar una entrada
	"bytes"
	"fmt"
	"os"
	"strings" // PARA HACER EL STRIM() EN LAS CADENAS
)

/*
un archivo .y esta compuesto por 4 secciones
- importes , uniones o declaraciones de tokenes , declaracion de gramatica , Segmento de codigo  para las funciones
*/

//line sint.y:19
type yySymType struct {
	yys         int
	NoTerminal  string
	str         string // DEFINO EL TIPO  DE MIS TERMINALES , EN ESTE CASO TODOS LOS QUE ESTEN EN %type<token> lo que va devolver es un tipo string
	tokenEntero int64
}

const NUMERO = 57346
const REP = 57347
const CM_RUTA = 57348
const CM_NOMBRE = 57349
const VD_ID_NUMERO = 57350
const EXTENSION_DSK = 57351
const B = 57352
const E = 57353
const L = 57354
const RF = 57355
const BF = 57356
const FF = 57357
const WF = 57358
const K = 57359
const M = 57360
const CHGRP = 57361
const GRP = 57362
const PAUSE = 57363
const COMANDO_ID = 57364
const R = 57365
const CHOWN = 57366
const CP = 57367
const DEST = 57368
const FIND = 57369
const CAT = 57370
const MV = 57371
const RM = 57372
const REN = 57373
const P = 57374
const MKFILE = 57375
const MKDIR = 57376
const LOGOUT = 57377
const ID = 57378
const FILE_N = 57379
const EDIT = 57380
const MKGRP = 57381
const RMGRP = 57382
const USR = 57383
const MOUNT = 57384
const RMDISK = 57385
const FLECHA = 57386
const PATH = 57387
const ADD = 57388
const EXEC = 57389
const RUTA = 57390
const MKDISK = 57391
const SIZE = 57392
const NAME = 57393
const UNIT = 57394
const FDISK = 57395
const TYPE = 57396
const FIT = 57397
const DELETE = 57398
const fast = 57399
const full = 57400
const UNMOUNT = 57401
const MKFS = 57402
const PWD = 57403
const RMUSR = 57404
const MKURS = 57405
const CHMOD = 57406
const UGO = 57407
const CONT = 57408

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMERO",
	"REP",
	"CM_RUTA",
	"CM_NOMBRE",
	"VD_ID_NUMERO",
	"EXTENSION_DSK",
	"B",
	"E",
	"L",
	"RF",
	"BF",
	"FF",
	"WF",
	"K",
	"M",
	"CHGRP",
	"GRP",
	"PAUSE",
	"COMANDO_ID",
	"R",
	"CHOWN",
	"CP",
	"DEST",
	"FIND",
	"CAT",
	"MV",
	"RM",
	"REN",
	"P",
	"MKFILE",
	"MKDIR",
	"LOGOUT",
	"ID",
	"FILE_N",
	"EDIT",
	"MKGRP",
	"RMGRP",
	"USR",
	"MOUNT",
	"RMDISK",
	"FLECHA",
	"PATH",
	"ADD",
	"EXEC",
	"RUTA",
	"MKDISK",
	"SIZE",
	"NAME",
	"UNIT",
	"FDISK",
	"TYPE",
	"FIT",
	"DELETE",
	"fast",
	"full",
	"UNMOUNT",
	"MKFS",
	"PWD",
	"RMUSR",
	"MKURS",
	"CHMOD",
	"UGO",
	"CONT",
	"'-'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line sint.y:131

func leerArchivoDeEntrada(ruta string) {
	fmt.Println("")
	fmt.Println("")
	fmt.Println("							||||||||||||||||||||||||||||||||||")
	fmt.Println("							|||||| Analizando un archivo |||||")
	fmt.Println("							||||||||||||||||||||||||||||||||||")
	fmt.Println("")
	ARCHIVO, error := os.Open(QuitarComillas(ruta))
	algo_salio_mal := false
	if error != nil {
		fmt.Println("ERROR REPORTADO")
		algo_salio_mal = true
	}
	if !(algo_salio_mal) {
		yyDebug = 0
		yyErrorVerbose = true
		scanner := bufio.NewScanner(ARCHIVO)
		entrada := ""
		for scanner.Scan() {
			linea_entrada := scanner.Text()
			linea_entrada = strings.TrimSpace(linea_entrada) // 	QUITO LOS ESPACIOS A LOS LADOS
			entrada = entrada + linea_entrada
			var listo_para_analizar bool = true
			// PREGUNTA SI TIENE UN CARACTER PARA CONTINUAR CON LA SIGUIENTE LINEA
			if len(entrada) >= 2 && entrada[len(entrada)-1] == '*' && entrada[len(entrada)-2] == '\\' {
				listo_para_analizar = false // TENGO QUE CONCATENAR LA ENTRADA ANTERIOR CON LA LINEA ACTUAL
				entrada = QuitarSimboloNextLine(entrada)
			}

			if listo_para_analizar {
				fmt.Println("EJECUTANDO>> " + entrada)
				l := nuevo_lexico__(bytes.NewBufferString(entrada), os.Stdout, "file.name") // ESTA FUNCION VIENE DEL ANALIZADOR LEXICO
				yyParse(l)
				entrada = "" //limpio la entrada
			}
		}
	}
	fmt.Println("")
	fmt.Println("							...Archivo terminado de analizar...")
	fmt.Println("")
}

func AnalizarComando() {
	puntero_lector := bufio.NewReader(os.NewFile(0, "stdin"))
	yyDebug = 0
	yyErrorVerbose = true
	for { // ciclo infinito
		var entrada string
		var bandera_todo_bien bool

		fmt.Printf(">> ")
		if entrada, bandera_todo_bien = leerLineComando(puntero_lector); bandera_todo_bien {
			entrada = strings.TrimSpace(entrada)

			if len(entrada) >= 2 && entrada[len(entrada)-1] == '*' && entrada[len(entrada)-2] == '\\' {
				entrada = QuitarSimboloNextLine(entrada)
				for {
					fmt.Print("continua esa linea>>")
					temporal := ""
					temporal, bandera_todo_bien = leerLineComando(puntero_lector)
					entrada += temporal
					entrada = strings.TrimSpace(entrada)
					if entrada[len(entrada)-1] != '*' && entrada[len(entrada)-2] != '\\' {
						break
					} else {
						entrada = QuitarSimboloNextLine(entrada)
					}
				}

			}
			l := nuevo_lexico__(bytes.NewBufferString(entrada), os.Stdout, "file.name") // ESTA FUNCION VIENE DEL ANALIZADOR LEXICO
			yyParse(l)
		} else {
			break
		}
	}
}

func leerLineComando(puntero_lector *bufio.Reader) (string, bool) {
	salida, err := puntero_lector.ReadString('\n')
	if err != nil {
		return "", false
	}
	return salida, true
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 106

var yyAct = [...]int{
	82, 27, 24, 22, 18, 19, 15, 37, 43, 98,
	99, 14, 36, 38, 39, 31, 40, 41, 42, 45,
	30, 32, 33, 84, 104, 46, 101, 8, 81, 79,
	74, 72, 75, 34, 28, 83, 51, 48, 71, 70,
	69, 68, 67, 66, 65, 64, 63, 62, 13, 11,
	26, 61, 50, 2, 60, 10, 59, 58, 57, 12,
	56, 55, 54, 53, 52, 106, 21, 103, 102, 91,
	92, 23, 88, 77, 78, 49, 47, 17, 105, 86,
	87, 94, 95, 96, 100, 80, 73, 35, 20, 97,
	90, 89, 85, 6, 29, 44, 16, 5, 76, 4,
	3, 7, 93, 1, 9, 25,
}

var yyPact = [...]int{
	6, -1000, -61, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-63, -62, -64, -65, -66, -11, -63, -1000, -30, -12,
	-64, -1000, -38, -65, -26, -66, -1000, 30, 20, -1000,
	19, 18, 17, 16, 14, -1000, 13, 12, 10, 7,
	3, 2, 1, 0, -1000, -1, -2, -1000, -3, -4,
	-5, -6, -17, 82, -18, 23, 56, -19, 81, -20,
	-13, 62, 58, 67, -48, 80, -22, -13, 31, -24,
	70, 29, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 105, 66, 104, 103, 102, 101, 0, 100, 99,
	98, 97, 96, 77, 93, 92, 91, 89, 50, 71,
	88,
}

var yyR1 = [...]int{
	0, 4, 4, 4, 8, 8, 8, 8, 8, 8,
	6, 6, 19, 19, 11, 9, 12, 12, 13, 13,
	13, 13, 10, 10, 15, 15, 15, 14, 20, 20,
	2, 2, 2, 2, 2, 2, 2, 2, 17, 17,
	5, 5, 5, 16, 16, 16, 7, 7, 3, 1,
	1, 18, 18, 18, 18,
}

var yyR2 = [...]int{
	0, 0, 5, 1, 1, 1, 1, 1, 1, 1,
	3, 1, 4, 4, 5, 2, 2, 1, 4, 4,
	4, 4, 1, 1, 1, 1, 1, 2, 2, 1,
	4, 4, 4, 4, 4, 4, 4, 4, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
	1, 4, 4, 4, 4,
}

var yyChk = [...]int{
	-1000, -4, 47, -8, -9, -11, -14, -6, 21, -3,
	49, 43, 53, 42, 5, 67, -12, -13, 67, 67,
	-20, -2, 67, -19, 67, -1, -18, 67, 45, -13,
	50, 45, 51, 52, 45, -2, 50, 45, 51, 52,
	54, 55, 56, 46, -19, 45, 51, -18, 7, 45,
	22, 6, 44, 44, 44, 44, 44, 44, 44, 44,
	44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
	44, 44, 48, 4, 48, 9, -10, 17, 18, 48,
	4, 48, -7, 48, 36, -15, 17, 18, 10, -16,
	32, 11, 12, -5, 14, 15, 16, -17, 57, 58,
	4, 48, -7, 36, 48, 8, 36,
}

var yyDef = [...]int{
	1, -2, 0, 3, 4, 5, 6, 7, 8, 9,
	0, 0, 0, 11, 0, 0, 15, 17, 0, 0,
	27, 29, 0, 0, 0, 48, 50, 0, 0, 16,
	0, 0, 0, 0, 0, 28, 0, 0, 0, 0,
	0, 0, 0, 0, 10, 0, 0, 49, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 2, 18, 19, 20, 21, 22, 23, 14,
	30, 31, 32, 46, 47, 33, 24, 25, 26, 34,
	43, 44, 45, 35, 40, 41, 42, 36, 38, 39,
	37, 12, 13, 51, 52, 53, 54,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 67,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sint.y:39
		{
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sint.y:40
		{
			leerArchivoDeEntrada(yyDollar[5].str)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:48
		{
			pausar_()
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sint.y:52
		{
			crearMontaje(QuitarComillas(Path_), QuitarComillas(Name_))
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:53
		{
			mostrarMounts()
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:55
		{
			Path_ = yyDollar[4].str
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:56
		{
			Name_ = yyDollar[4].NoTerminal
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sint.y:59
		{
			EliminarDisco(yyDollar[5].str)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sint.y:61
		{
			CrearDisco(Size_, Path_, Name_, Unit_m_)
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:66
		{
			Size_ = yyDollar[4].str
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:67
		{
			Path_ = yyDollar[4].str
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:68
		{
			Name_ = yyDollar[4].str
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:69
		{
			Unit_m_ = yyDollar[4].NoTerminal
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:74
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:75
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:78
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:79
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:80
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sint.y:84
		{
			MetodosParticiones(Path_, Name_, Size_, FIT_, OPCION_DELETE_, add_, tipo_particion_, Unit_k_)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:90
		{
			Size_ = yyDollar[4].str
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:91
		{
			Path_ = yyDollar[4].str
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:92
		{
			Name_ = yyDollar[4].NoTerminal
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:93
		{
			Unit_k_ = yyDollar[4].NoTerminal
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:94
		{
			tipo_particion_ = yyDollar[4].NoTerminal
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:95
		{
			FIT_ = yyDollar[4].NoTerminal
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:96
		{
			OPCION_DELETE_ = yyDollar[4].NoTerminal
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:97
		{
			add_ = yyDollar[4].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:100
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:101
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:104
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:105
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:106
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:109
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:110
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:111
		{
			yyVAL.NoTerminal = yyDollar[1].str
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:115
		{
			yyVAL.NoTerminal = QuitarComillas(yyDollar[1].str)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sint.y:116
		{
			yyVAL.NoTerminal = QuitarComillas(yyDollar[1].str)
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sint.y:118
		{
			generarReporte()
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:123
		{
			Name_ = yyDollar[4].str
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:124
		{
			Path_ = QuitarComillas(yyDollar[4].str)
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:125
		{
			Id_vdlentraNumero_ = yyDollar[4].str
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sint.y:126
		{
			Commando_Ruta_ = yyDollar[4].str /*aun no se usara*/
		}
	}
	goto yystack /* stack new state and value */
}
